# Generated by Django 4.1.13 on 2024-01-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('AlumnoId', models.AutoField(primary_key=True, serialize=False)),
                ('AlumnoNombre', models.CharField(max_length=50)),
                ('AlumnoPrograma', models.CharField(max_length=50)),
                ('FechaDeIngreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('FacultadId', models.AutoField(primary_key=True, serialize=False)),
                ('FacultadNombre', models.CharField(max_length=50)),
            ],
        ),
    ]
